name: simple_secure_storage_windows
description: Windows implementation of the Simple Secure Storage plugin.
homepage: https://github.com/Skyost/SimpleSecureStorage
repository: https://github.com/Skyost/SimpleSecureStorage/tree/master/packages/simple_secure_storage_windows
issue_tracker: https://github.com/Skyost/SimpleSecureStorage/issues
version: 0.3.0

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: '>=3.24.3'

flutter:
  plugin:
    platforms:
      implements: simple_secure_storage
      windows:
        pluginClass: SimpleSecureStorageWindowsPluginCApi

dependencies:
  flutter:
    sdk: flutter
  simple_secure_storage_platform_interface:
    git:
      url: git@github.com:camrongiuliani/SimpleSecureStorage.git
      ref: 0.0.5
      path: packages/simple_secure_storage_platform_interface

dependency_overrides:
  simple_secure_storage_platform_interface:
    path: ../simple_secure_storage_platform_interface/
