name: simple_secure_storage
description: "Simple and secure storage for Flutter. Supports Android, iOS, macOS, Windows and web !"
version: 0.3.0
homepage: https://github.com/Skyost/SimpleSecureStorage
repository: https://github.com/Skyost/SimpleSecureStorage/tree/master/packages/simple_secure_storage
issue_tracker: https://github.com/Skyost/SimpleSecureStorage/issues
funding:
  - https://ko-fi.com/Skyost
  - https://paypal.me/Skyost

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: '>=3.24.3'

dependencies:
  flutter:
    sdk: flutter
  simple_secure_storage_platform_interface:
    git:
      url: git@github.com:camrongiuliani/SimpleSecureStorage.git
      ref: 0.0.4
      path: packages/simple_secure_storage_platform_interface
  simple_secure_storage_android:
    git:
      url: git@github.com:camrongiuliani/SimpleSecureStorage.git
      ref: 0.0.4
      path: packages/simple_secure_storage_android
  simple_secure_storage_darwin:
    git:
      url: git@github.com:camrongiuliani/SimpleSecureStorage.git
      ref: 0.0.4
      path: packages/simple_secure_storage_darwin
  simple_secure_storage_windows:
    git:
      url: git@github.com:camrongiuliani/SimpleSecureStorage.git
      ref: 0.0.4
      path: packages/simple_secure_storage_windows
  simple_secure_storage_linux:
    git:
      url: git@github.com:camrongiuliani/SimpleSecureStorage.git
      ref: 0.0.4
      path: packages/simple_secure_storage_linux
  simple_secure_storage_web:
    git:
      url: git@github.com:camrongiuliani/SimpleSecureStorage.git
      ref: 0.0.4
      path: packages/simple_secure_storage_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  melos: ^4.1.0

flutter:
  plugin:
    platforms:
      android:
        default_package: simple_secure_storage_android
      ios:
        default_package: simple_secure_storage_darwin
      macos:
        default_package: simple_secure_storage_darwin
      windows:
        default_package: simple_secure_storage_windows
      linux:
        default_package: simple_secure_storage_linux
      web:
        default_package: simple_secure_storage_web
